/*
문제
'경제' 카테고리에 속하는 도서들의
도서 ID(BOOK_ID), 저자명(AUTHOR_NAME), 출판일(PUBLISHED_DATE) 리스트를 출력하는 SQL문을 작성해주세요.
결과는 출판일을 기준으로 오름차순 정렬해주세요.

https://school.programmers.co.kr/learn/courses/30/lessons/144854
 */


SELECT A.BOOK_ID,B.AUTHOR_NAME,TO_CHAR(A.PUBLISHED_DATE,'YYYY-MM-DD')
FROM BOOK A INNER JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY = '경제'
ORDER BY A.PUBLISHED_DATE

/*
SELECT A.BOOK_ID,B.AUTHOR_NAME,DATE_FORMAT(A.PUBLISHED_DATE,'%Y-%m-%d')
FROM BOOK A INNER JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY = '경제'
ORDER BY A.PUBLISHED_DATE
*/