CREATE TABLE USED_GOODS_USER
(
    USER_ID         VARCHAR(50)  NOT NULL,
    NICKNAME        VARCHAR(100) NOT NULL,
    CITY            VARCHAR(100) NOT NULL,
    STREET_ADDRESS1 VARCHAR(100) NOT NULL,
    STREET_ADDRESS2 VARCHAR(100),
    TLNO            VARCHAR(20)  NOT NULL
);



INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('kwag98', '미금러', '성남시', '분당구 정자로 115', '102-1004', '1032114944');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('goung12', '티트티', '성남시', '분당구 정자일로 27', '1004-1004', '1032174945');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('keel1990', '죠르디', '성남시', '분당구 미금로 215', '201동 204호', '1052124941');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('lee871201', '니니즈', '성남시', '분당구 정자일로 75', '108동 2101호', '1012612312');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('haphli01', '이카루스,', '성남시', '경기도 성남시 분당구 성남대로171', 'A동 205호', '102414949');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('hanju23', '라이언즈', '성남시', '분당구 정자로 231', '304호', '1012352122');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('yawoong67', 'helloworld', '성남시', '분당구 미금로 203', '2018-1009', '1029384910');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('hong02', '자바한명', '성남시', '분당구 정자일로 210', '4동 501호', '1022039488');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('hoho1112', '코딩쟁이', '성남시', '분당구 정자일로 1', '202호', '1032112939');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('hwahwa2', '당근', '성남시', '분당구 내정로 55', '305호', '1032113454');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('s2s2123', '이회장', '성남시', '분당구 정자로 2', '1005동 1004호', '1022116664');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('tkfkdgo1', '금사자', '성남시', '분당구 느티로 2', '31', '1011235555');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('skeh123', '느티매미', '성남시', '분당구 느티로 70', 'A동 1002호', '1045661232');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('whgkdkgo1', '청년사장', '성남시', '분당구 성남대로 449', '', '1012368888');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('hakho11', '청솔다람쥐', '성남시', '분당구 정자일로 80', '102-1004', '1084534941');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('hakju88', '에코', '성남시', '분당구 미금일로 57', '1003-401', '1032114231');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('sangyoung58', '보라보라', '성남시', '분당구 미금일로 30', '105-201', '1077721941');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('miyeon89', '러브러브', '성남시', '분당구 내정로 152', 'C동 204호', '1032116456');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('xlaortm1', '투더문', '성남시', '분당구 내정로165번길 35', '104-1202', '1032555431');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('zkzkdh1', '후후후', '성남시', '분당구 내정로 35', '가동 1202호', '1032777543');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('spdlqj12', '크크큭', '성남시', '분당구 수내로 206', '2019동 801호', '1087234922');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('xlqpfh2', '잉여킹', '성남시', '분당구 수내로 1', '001-004', '1064534911');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('dhfkzmf09', '찐찐', '성남시', '분당구 수내로 13', 'A동 1107호', '1053422914');
INSERT INTO USED_GOODS_USER(user_id, nickname, city, street_address1, street_address2, tlno)
VALUES ('dlPcks90', '썹썹', '성남시', '분당구 수내로 74', '401호', '1034573944');